spring:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    platform: h2
    url: jdbc:h2:file:~/Content
    name: Content
    username: content
    password: password
    driverClassName: org.h2.Driver
    initialization-mode: embedded
    # url: jdbc:postgresql://localhost:5432
    # username: postgres
    # password: password
logging:
  level:
    org:
      springframework:
        jdbc: DEBUG