version: '3.8'

# https://hub.docker.com/ /postgres/

services:
  db:
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres 
      POSTGRES_PASSWORD: password 
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql

